server:
  servlet:
    context-path: /device-test

logging:
  level:
    org: info
  file:
    name: main.log
  logback:
    rollingpolicy:
      max-file-size: 30MB
      max-history: 7

spring:
  datasource:
    url: jdbc:mysql://localhost/device_test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
