spring:
  datasource:
    url: jdbc:mysql://localhost/device_test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: zhangwei
    password: zhangwei